secondproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('', RedirectView.as_view(url='/todo/')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/detail/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

todo/models.py
from django.db import models
from django.urls import reverse

class Task(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse('todo:index')

todo/views.py
from django.views import generic
from .models import Task
from django.urls import reverse_lazy
from django.http.response import HttpResponse

class IndexView(generic.ListView):
    model = Task

class DetailView(generic.DetailView):
    model = Task

class CreateView(generic.edit.CreateView):
    model = Task
    fields = '__all__'

class UpdateView(generic.edit.UpdateView):
    model = Task
    fields = '__all__'

class DeleteView(generic.edit.DeleteView):
    model = Task
    success_url = reverse_lazy('todo:index')

todo/templates/todo/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='with=device-width, initial-scale=1, shrink-to-fit=no'>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <title>お金管理App</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- css -->
    <style type="text/css">
      body {padding-top: 80px;}
      .tr-color {background-color: #ff9999;}
    </style>
  </head>
  <body>
    <nav class='navbar navbar-expand-md navbar-dark bg-danger fixed-top'>
      <a class='navbar-brand ml-5' href='{% url "todo:index" %}'><i class="fas fa-piggy-bank mr-2"></i>お金管理App<i class="fas fa-piggy-bank ml-2"></i></a>
    </nav>
    <div class='container mt-5'>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

todo/templates/todo/task_detail.html
{% extends './base.html' %}
{% block content %}
  <h1>タスクの内容</h1>
  <p>{{ task.category }}</p>

  <div>
    <a href='{% url "todo:index" %}' class='btn btn-outline-primary'>一覧</a>
  </div>
{% endblock %}

todo/templates/todo/task_form.html
{% extends './base.html' %}
{% block content %}
<div>
  <div class="row">
    <div class="col-md-4">
      <h1 class="pb-3"><i class="fas fa-edit"></i>{{ object|yesno:'編集,作成' }}内容</h1>
      <!-- ボタン -->
      <form action='' method='post'>{% csrf_token %}
        {{ form.as_p }}
        <button type='submit' class='submit btn btn-outline-secondary'><i class="fas fa-pencil-alt mr-2"></i>{{ object|yesno:'編集,作成' }}</button>
      </form>
      <div>
        <a href='JavaScript:history.back()' class='submit btn btn-outline-danger'><i class="fas fa-undo mr-2"></i>戻る</a>
      </div>
    </div>
    <div class="col-md-4 p-2">
      <table class="table table-striped">
        <thead>
          <tr class="tr-color">
            <th scope="col"><i class="fas fa-star-of-david"></i></th>
            <th scope="col">支払項目</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">住居</th>
            <td>家賃</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>食費</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>電気代</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>ガス代</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>水道代</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>ネット代</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-4 table-striped p-2">
      <table class="table">
        <thead>
          <tr class="tr-color">
            <th scope="col"><i class="fas fa-star-of-david"></i></th>
            <th scope="col">支払項目</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">税・保険</th>
            <td>健康保険</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>年金</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>住民税</td>
          </tr>
          <tr>
            <th scope="row">その他</th>
            <td>携帯代</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>カード代</td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td>奨学金</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

todo/templates/todo/task_list.html
{% extends './base.html' %}
{% block content %}
  <!-- css -->
  <style type="text/css">
    .embed-responsive-item {
      display: block;
      margin: 0 auto;
    }
  </style>
  <!-- Taskテーブル -->
  <section>
    <h1 class="pb-3"><i class="fas fa-yen-sign mr-2"></i>今月の支払い</h1>
    <div class="row">
      <div class="col-md-8">
        <table class='table table-striped table-hover'>
          <tr>
            <th scope="col" class="pl-5">支払項目</th>
          </tr>
          {% for task in object_list %}
          <tr>
            <td class="pl-5">
              {{ task.category }}
              <a href='{% url "todo:update" task.pk %}' class='btn btn-outline-secondary float-right'><i class="fas fa-star-of-david mr-2"></i>編集</a>
              <form action='{% url "todo:delete" task.pk %}' method='post' class='d-inline'>{% csrf_token %}
                <button class='btn btn-outline-danger float-right'><i class="fas fa-kiss-wink-heart mr-2"></i>削除</button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </table>
        <div class='pb-3'>
          <a href='{% url "todo:create" %}' class='btn btn-outline-secondary'><i class="fas fa-star-of-david mr-2"></i>新規作成</a>
        </div>
      </div>
      <!-- 天気予報API -->
      <div class="col-md-4">
        <iframe class="embed-responsive-item border border-warning"
                id='weathermap'
                src='https://api.openweathermap.org/data/2.5/weather?q=Kobe&mode=html&appid=df691d3eb3927b60d8e97c3ce81f2f16'
                height='320'
                frameborder='10'>
        </iframe>
    </div>
  </section>


{% endblock %}